---
- name: Install Drush
  shell: |
    wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
    chmod +x drush.phar
    sudo mv drush.phar /usr/local/bin/drush
    drush self-update