---
- name: Roles for all hosts
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  pre_tasks:
#    - name: Load stage secret vars
#      tags: always
#      include_vars: stage_vars/{{ stage }}_secrets.yml
    - name: Load stage vars
      tags: always
      include_vars: stage_vars/{{ stage }}.yml
      include_vars: stage_vars/secret.yml
  roles:
    - { role: common, tags: common }
    - { role: supla, tags: supla }
    - { role: nginx, tags: nginx }
    - { role: php, tags: php }

  vars:
    - nginx_enable_monitor: true  # default=true, will setup default server responding to /monitor/monitor.html
    - nginx_package_source: nginx  # default=nginx, options: nginx, openresty
    - nginx_redirect_to_https: true # default=false, will redirect to https if $http_x_forwarded_proto != "https"
    - nginx_sites:
         - name: "{{ product }}"
           enabled: true
           type: php
           redirect_to_https: false
           server: "{{ web_host }}"
           listen:
             - "*:80"
             - "*:81 http2 proxy_protocol"
           log_path: /data/logs/{{ product }}
           root: /data/home/{{ product }}/public
           socket_type: 'unix:'
           socket_location: '/usr/local/zend/tmp/php-fpm.sock'
    - php_version: '7.0' # Don't forget quotes!
    - php_enable_fpm: true

  environment:
    SITE_NAME: "{{ V_SITE_NAME }}"
    COOKIE_DOMAIN: "{{ V_COOKIE_DOMAIN }}"
    BASE_URL: "{{ V_BASE_URL }}"
    FILE_PRIVATE_PATH: "{{ V_FILE_PRIVATE_PATH }}"

    # Database
    DB_NAME: "{{ rds_db_name }}"
    DB_USERNAME: "{{ rds_db_username }}"
    DB_PASSWORD: "{{ rds_db_password }}"
    DB_HOSTNAME: "{{ rds_db_host }}"
    DB_PORT: "{{ rds_db_port }}"

    FILE_PUBLIC_BASE_URL: "{{ V_FILE_PUBLIC_BASE_URL }}"

    ## Sacu
    SAPI_CLIENT_ID: "{{ V_SAPI_CLIENT_ID }}"
    SAPI_CLIENT_SECRET: "{{ V_SAPI_CLIENT_SECRET }}"
    SAPI_SUBSCRIPTION_KEY: "{{ V_SAPI_SUBSCRIPTION_KEY }}"
    SAPI_BASE_URI: "{{ V_SAPI_BASE_URI }}"
    SACU_ENDPOINT_BASE_URI: "{{ V_SACU_ENDPOINT_BASE_URI }}"
    SACU_SANOMA_ACCOUNT_SETTINGS_URI: "{{ V_SACU_SANOMA_ACCOUNT_SETTINGS_URI }}"
    SACU_AUTHORIZED_URI: "{{ V_SACU_AUTHORIZED_URI }}"
    SACU_SHARED_COOKIE_DOMAIN: "{{ V_SACU_SHARED_COOKIE_DOMAIN }}"

    # Cos
    COS_API_KEY: "{{ V_COS_API_KEY }}"
    COS_BASE_URL: "{{ V_COS_BASE_URL }}"

    # AWS S3
    S3_KEY: "{{ V_S3_KEY }}"
    S3_SECRET: "{{ V_S3_SECRET }}"
    S3_BUCKET: "{{ V_S3_BUCKET }}"
    S3_CNAME: "{{ V_S3_CNAME }}"

