- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
    - git

- block:
    - name: Create directories
      file: 
        path={{ item }}
        state=directory
      with_items:
        - /data/home/{{ product }}
        - /data/home/{{ product }}/public
        - /data/home/{{ product }}/public/monitor

    - name: Create default files
      template: >
        src={{ item }}.j2
        dest=/data/home/{{ product }}/public/{{ item }}
        mode=0644
      with_items:
        - "404.html"
        - "index.html"
        - "index.php"
  
    - name: Install Postgresql client package
      yum: name={{ item }}
          state=present
      with_items:
        - postgresql
  become_user: root
  become: true
  when: stage != "production"