- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
    - git

- name: Ansible delete previous web directory
  file:
    path: /data/home/{{ product }}/public
    state: absent

- block:
    - name: Create directories
      file: 
        path={{ item }}
        state=directory
      with_items:
        - /data/home/{{ product }}
        - /data/home/{{ product }}/public
        - /data/home/{{ product }}/public/monitor

#    - name: Create default files
#      template: >
#        src={{ item }}.j2
#        dest=/data/home/{{ product }}/public/{{ item }}
#        mode=0644
#      with_items:
#        - "404.html"
#        - "index.html"
#        - "index.php"

- pip:
    name: botocore

- pip:
    name: boto3

- name: download artifact
  aws_s3:
    ignore_nonexistent_bucket: true
    aws_access_key: "{{ s3_access_key[0] }}"
    aws_secret_key: "{{ s3_secret_key[0] }}"
    bucket: "snm-nl-nelo-novelist-test-va-webbucket-25433c0e"
    object: "/novelist.tar.gz"
    dest: "/data/home/{{ product }}/novelist.tar.gz"
    mode: get
    region: eu-west-1
    retries: 2

- name: Extract novelist.tar.tgz
  unarchive:
    src: /data/home/{{ product }}/novelist.tar.gz
    dest: /data/home/{{ product }}/public
    remote_src: yes

  - name: Create settings.local.php
    template: >
      src={{ item }}.j2
      dest=/data/home/{{ product }}/public/sites/web/default/{{ item }}
      mode=0644
    with_items:
      - "settings.local.php"


#    - name: Install Postgresql client package
#      yum: name={{ item }}
#          state=present
#      with_items:
#        - postgresql
#  become_user: root
#  become: true
#  when: stage != "production"