---
- name: Setup directories owner root
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: yes
  with_items:
    - /var/run/nginx
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Setup directories owner nginx
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: nginx
  become: yes
  with_items:
    - /var/nginx/client_body_temp
    - /var/nginx/proxy_temp
    - "{{ nginx_cache_root }}"

- name: Setup cache directories
  file:
    path: "{{ nginx_cache_root }}/{{ item.key_zone }}"
    state: directory
    mode: 0755
    owner: nginx
  become: yes
  with_items: "{{ nginx_cache_paths }}"

- name: Update nginx config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  when: item.execute | default(True)
  with_items:
    - { src:  nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src:  real_ip_from_elb.conf.j2, dest: /etc/nginx/conf.d/real_ip_from_elb.conf, execute: "{{ nginx_real_ip }}" }
  become: yes
  notify:
    - reload nginx

- name: Check if /etc/nginx/conf.d/default.conf exists
  stat:
    path: /etc/nginx/conf.d/default.conf
  register: stat_default_conf
  when: not nginx_enable_default_conf

- name: Check if /etc/nginx/conf.d/default.conf.DISABLED exists
  stat:
    path: /etc/nginx/conf.d/default.conf.DISABLED
  register: stat_default_conf_disabled
  when: nginx_enable_default_conf

- name: Disable /etc/nginx/conf.d/default.conf
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.DISABLED
  become: yes
  when: stat_default_conf.stat is defined and stat_default_conf.stat.exists
  notify:
    - reload nginx

- name: Enable /etc/nginx/conf.d/default.conf
  command: mv /etc/nginx/conf.d/default.conf.DISABLED /etc/nginx/conf.d/default.conf
  become: yes
  when: stat_default_conf_disabled.stat is defined and stat_default_conf_disabled.stat.exists
  notify:
    - reload nginx

- name: Enable nginx at startup & ensure started
  become: yes
  service:
    name: nginx
    enabled: yes
