---
- name: add nginx-release repo
  template:
    src: nginx-release.repo.j2
    dest: /etc/yum.repos.d/nginx-release.repo
    mode: 0644
  become: yes

- name: Install nginx
  yum:
    name: nginx
    state: present
    enablerepo: nginx-release
  become: yes
